<?php
declare(strict_types=1);

namespace SetBased\Abc;

/**
 * Class for holding all constants generated by PhpStratum.
 */
class C
{
  //--------------------------------------------------------------------------------------------------------------------
  /**
   * @setbased.stratum.constants
   *
   * Below this doc block constants will be inserted by PhpStratum.
   */
  const CMP_ID_ABC          = 2;
  const CMP_ID_SYS          = 1;
  const LTN_ID_ENTITY_LOCK1 = 1;
  const LTN_ID_ENTITY_LOCK2 = 2;

  //--------------------------------------------------------------------------------------------------------------------
}

//----------------------------------------------------------------------------------------------------------------------
