build:
  environment:
    mysql: 5.7

  tests:
    before:
      - export PLAISIO_CONFIG_DIR=test
      - ./bin/phing kernel
    override:
      - command: './bin/phing unit'
        coverage:
          file:   'test/coverage.xml'
          format: 'php-clover'

