language: php
php:
  - '7.3'
  - '7.4'

sudo: true

addons:
  mariadb: '10.2'

before_install:
  - mysql --version
  - mysql -u root -e "set global binlog_format = 'row';"
  - mysql -u root -e "set global log_bin_trust_function_creators = 1;"

install:
  - composer self-update
  - composer update

script:
  - ./bin/phing unit
