language: php
php:
  - '7.0'
  - '7.1'
  - nightly
  
sudo: true

addons:
  mariadb: 10.2

before_install:
  - mysql --version
  - mysql -u root -e "set global binlog_format = 'row';"
  - mysql -u root -e "set global log_bin_trust_function_creators = 1;"
  
install:
  - composer self-update
  - cp test/C.txt test/C.php
  - composer update
    
script: 
  - ./bin/phing unit

after_script:
  - mv test/C.php test/C.txt